version: '3.2'
services:
  almdb:
    image: postgres:11.0-alpine
    ports:
      - 5432:5432
    command: ["postgres", "-c", "max_prepared_transactions=100", "-c", "shared_preload_libraries=pg_stat_statements,pg_trgm", "-c", "pg_stat_statements.max=10000", "-c", "pg_stat_statements.track=all", "-c", "autovacuum=on", "-c", "track_counts=on", "-c", "log_autovacuum_min_duration=250ms", "-c", "autovacuum_vacuum_scale_factor=0.2", "-c", "autovacuum_vacuum_threshold=50", "-c", "autovacuum_analyze_scale_factor=0.1", "-c", "autovacuum_analyze_threshold=50", "-c", "autovacuum_vacuum_cost_limit=-1", "-c", "autovacuum_vacuum_cost_delay=20ms", "-c", "vacuum_cost_page_hit=1", "-c", "vacuum_cost_page_miss=10", "-c" ,"vacuum_cost_page_dirty=20"]
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    networks:
      core:
        aliases:
          - almdb
volumes:
  dbdata:
networks:
  core:
    driver: bridge
